"""my table

Revision ID: d2f953cfb749
Revises: 
Create Date: 2018-11-06 10:47:45.532223

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2f953cfb749'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AF',
    sa.Column('ids', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('article', sa.String(length=2048), nullable=True),
    sa.PrimaryKeyConstraint('ids')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AF')
    # ### end Alembic commands ###
